language: node_js
node_js:
  - "10.4.1"
sudo: true
cache: npm

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run test-headless
  - npm run-script build:content
  - ng build --prod --base-href $base_href
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/
  keep-history: true
  on:
    branch: master